
package main;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RTM
 */
public class Home extends javax.swing.JFrame {

   /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
        


}
     public String searchtext(){
             String str = Search_jTextField.getText(); 
             return str;
         }
    

    Home(CustomerSearch aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        logo_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search_jTextField = new javax.swing.JTextField();
        Search_jButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        Button_jPanel = new javax.swing.JPanel();
        Home_jButton = new javax.swing.JButton();
        Home_jButton1 = new javax.swing.JButton();
        Home_jButton2 = new javax.swing.JButton();
        Home_jButton3 = new javax.swing.JButton();
        Home_jButton4 = new javax.swing.JButton();
        Home_jButton5 = new javax.swing.JButton();
        Data_jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, logo_Label, org.jdesktop.beansbinding.ELProperty.create("${icon}"), logo_Label, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("COCA-COLA KWANZA LIMITED");

        jLabel2.setFont(new java.awt.Font("Wide Latin", 2, 12)); // NOI18N
        jLabel2.setText("APPLICATION FOR A LOAN COOLER");

        Search_jTextField.setToolTipText("SEARCH BY NAME");
        Search_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_jTextFieldActionPerformed(evt);
            }
        });

        Search_jButton.setText("Search");
        Search_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(logo_Label)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search_jButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_jButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Search_jTextField)))
                .addContainerGap())
        );

        Home_jButton.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton.setText("HOME");
        Home_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButtonActionPerformed(evt);
            }
        });

        Home_jButton1.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton1.setText("PENDING");
        Home_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButton1ActionPerformed(evt);
            }
        });

        Home_jButton2.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton2.setText("APPROVED");
        Home_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButton2ActionPerformed(evt);
            }
        });

        Home_jButton3.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton3.setText("UPDATE");
        Home_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButton3ActionPerformed(evt);
            }
        });

        Home_jButton4.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton4.setText("CONTRACTS");
        Home_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButton4ActionPerformed(evt);
            }
        });

        Home_jButton5.setBackground(new java.awt.Color(255, 0, 0));
        Home_jButton5.setText("REPORTS");
        Home_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Button_jPanelLayout = new javax.swing.GroupLayout(Button_jPanel);
        Button_jPanel.setLayout(Button_jPanelLayout);
        Button_jPanelLayout.setHorizontalGroup(
            Button_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Button_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Home_jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Home_jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Home_jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Home_jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        Button_jPanelLayout.setVerticalGroup(
            Button_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Home_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(Button_jPanel);

        javax.swing.GroupLayout Data_jPanelLayout = new javax.swing.GroupLayout(Data_jPanel);
        Data_jPanel.setLayout(Data_jPanelLayout);
        Data_jPanelLayout.setHorizontalGroup(
            Data_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        Data_jPanelLayout.setVerticalGroup(
            Data_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(Data_jPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_jTextFieldActionPerformed

    private void Home_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButtonActionPerformed

    private void Home_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButton1ActionPerformed
NewJPanel pending = new NewJPanel();
        Data_jPanel.setBackground(Color.red);
       jSplitPane1.setRightComponent( pending);
       

// Code of sub-components - not shown here

// Layout setup code - not shown here
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButton1ActionPerformed

    private void Home_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButton2ActionPerformed
Approved2 approved = new Approved2();
        Data_jPanel.setBackground(Color.red);
       jSplitPane1.setRightComponent( approved);        // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButton2ActionPerformed

    private void Home_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButton3ActionPerformed

Update2 update = new Update2();
        Data_jPanel.setBackground(Color.red);
       jSplitPane1.setRightComponent( update);        // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButton3ActionPerformed

    private void Home_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButton4ActionPerformed

    private void Home_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_jButton5ActionPerformed
Newreport myreport = new Newreport();
        Data_jPanel.setBackground(Color.red);
       jSplitPane1.setRightComponent( myreport);
               // TODO add your handling code here:
    }//GEN-LAST:event_Home_jButton5ActionPerformed

    private void Search_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_jButtonActionPerformed
CustomerSearch search = new CustomerSearch();
        Data_jPanel.setBackground(Color.red);
       jSplitPane1.setRightComponent( search);       // TODO add your handling code here:
    }//GEN-LAST:event_Search_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button_jPanel;
    private javax.swing.JPanel Data_jPanel;
    private javax.swing.JButton Home_jButton;
    private javax.swing.JButton Home_jButton1;
    private javax.swing.JButton Home_jButton2;
    private javax.swing.JButton Home_jButton3;
    private javax.swing.JButton Home_jButton4;
    private javax.swing.JButton Home_jButton5;
    private javax.swing.JButton Search_jButton;
    public javax.swing.JTextField Search_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel logo_Label;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
